#.preconfig file for pre commit workflow
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-case-conflict
    -   id: check-docstring-first
#    -   id: check-json not sure we have ant json files yet, but this could be used later
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: pretty-format-json
    -   id: trailing-whitespace