using System.ComponentModel.DataAnnotations;

namespace Annotations.Core.Entities;

public class ImageSeries
{
    /// <summary>
    /// <para>A unique number. Auto-generated by the database.</para>
    /// </summary>
    [Key]
    public long ImageSeriesId { get; set; }

    /// <summary>
    /// <para>User that created the image series.</para>
    /// </summary>
    [Required]
    public required User CreatedBy { get; set; }

    /// <summary>
    /// <para>The image series has a category.</para>
    /// </summary>
    [Required]
    public required string Category { get; set; }
}
