using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace Annotations.Core.Entities;

/// <summary>
/// Entity representing an image series. Means to arrange images for research jobs.
/// </summary>
public class ImageSeries
{
    /// <summary>
    /// A unique number. Auto-generated by the database.
    /// </summary>
    [Key]
    public long ImageSeriesId { get; set; }

    /// <summary>
    /// Collection of images in the image series.
    /// </summary>
    public ICollection<Image> Images { get; set; } = [];

    /// <summary>
    /// Image series entries. Intended for additional information, i.e. a list ordering.
    /// </summary>
    public ICollection<ImageSeriesEntry> ImageEntries { get; set; } = [];

    /// <summary>
    /// Name of image series.
    /// </summary>
    [Required]
    public required string Name { get; set; }

    /// <summary>
    /// The time and date that the image series was created.
    /// </summary>
    [Required]
    public required DateTime TimeCreated { get; set; }

    /// <summary>
    /// User that created the image series.
    /// </summary>
    [Required]
    public required User CreatedBy { get; set; }

    /// <summary>
    /// The image series has a category.
    /// </summary>
    [Required]
    public required string Category { get; set; }

    /// <summary>
    /// Marks this image series as deleted.
    /// </summary>
    public bool IsDeleted { get; set; }
}
