// <auto-generated />
using System;
using Annotations.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Annotations.API.Migrations
{
    [DbContext(typeof(AnnotationsDbContext))]
    [Migration("20250423150314_dbContextVesselTree")]
    partial class dbContextVesselTree
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Annotations.Core.Entities.Image", b =>
                {
                    b.Property<string>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeUploaded")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ImageId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Annotations.Core.Entities.ImageSeries", b =>
                {
                    b.Property<long>("ImageSeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("ImageSeriesId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("ImageSeries");
                });

            modelBuilder.Entity("Annotations.Core.Entities.ImageSeriesEntry", b =>
                {
                    b.Property<string>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ImageSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImageId", "ImageSeriesId");

                    b.HasIndex("ImageSeriesId");

                    b.ToTable("ImageSeriesEntry");
                });

            modelBuilder.Entity("Annotations.Core.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Annotations.Core.Entities.VesselPoint", b =>
                {
                    b.Property<int>("PointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("PointId");

                    b.ToTable("VesselPoints");
                });

            modelBuilder.Entity("Annotations.Core.Entities.VesselSegment", b =>
                {
                    b.Property<int>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndPointPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartPointPointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Thickness")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VesselTreeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SegmentId");

                    b.HasIndex("EndPointPointId");

                    b.HasIndex("StartPointPointId");

                    b.HasIndex("VesselTreeId");

                    b.ToTable("VesselSegments");
                });

            modelBuilder.Entity("Annotations.Core.Entities.VesselTree", b =>
                {
                    b.Property<int>("VesselTreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VesselTreeId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("VesselTrees");
                });

            modelBuilder.Entity("Annotations.Core.Entities.Image", b =>
                {
                    b.HasOne("Annotations.Core.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Annotations.Core.Entities.ImageSeries", b =>
                {
                    b.HasOne("Annotations.Core.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Annotations.Core.Entities.ImageSeriesEntry", b =>
                {
                    b.HasOne("Annotations.Core.Entities.Image", null)
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Annotations.Core.Entities.ImageSeries", null)
                        .WithMany("ImageEntries")
                        .HasForeignKey("ImageSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Annotations.Core.Entities.VesselSegment", b =>
                {
                    b.HasOne("Annotations.Core.Entities.VesselPoint", "EndPoint")
                        .WithMany()
                        .HasForeignKey("EndPointPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Annotations.Core.Entities.VesselPoint", "StartPoint")
                        .WithMany()
                        .HasForeignKey("StartPointPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Annotations.Core.Entities.VesselTree", null)
                        .WithMany("Segments")
                        .HasForeignKey("VesselTreeId");

                    b.Navigation("EndPoint");

                    b.Navigation("StartPoint");
                });

            modelBuilder.Entity("Annotations.Core.Entities.VesselTree", b =>
                {
                    b.HasOne("Annotations.Core.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Annotations.Core.Entities.ImageSeries", b =>
                {
                    b.Navigation("ImageEntries");
                });

            modelBuilder.Entity("Annotations.Core.Entities.VesselTree", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
