// <auto-generated />
using System;
using Annotations.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Annotations.API.Migrations
{
    [DbContext(typeof(AnnotationsDbContext))]
    [Migration("20250420173423_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Annotations.Core.Entities.Image", b =>
                {
                    b.Property<string>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeUploaded")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ImageId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Annotations.Core.Entities.ImageSeries", b =>
                {
                    b.Property<long>("ImageSeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ImageSeriesId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("ImageSeries");
                });

            modelBuilder.Entity("Annotations.Core.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ImageImageSeries", b =>
                {
                    b.Property<string>("ImagesImageId")
                        .HasColumnType("TEXT");

                    b.Property<long>("InImageSeriesImageSeriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImagesImageId", "InImageSeriesImageSeriesId");

                    b.HasIndex("InImageSeriesImageSeriesId");

                    b.ToTable("ImagesInImageSeries", (string)null);
                });

            modelBuilder.Entity("Annotations.Core.Entities.Image", b =>
                {
                    b.HasOne("Annotations.Core.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Annotations.Core.Entities.ImageSeries", b =>
                {
                    b.HasOne("Annotations.Core.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("ImageImageSeries", b =>
                {
                    b.HasOne("Annotations.Core.Entities.Image", null)
                        .WithMany()
                        .HasForeignKey("ImagesImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Annotations.Core.Entities.ImageSeries", null)
                        .WithMany()
                        .HasForeignKey("InImageSeriesImageSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
