openapi: 3.1.0
info:
  title: Annotations PerfusionTech
  description: |
    This API allows medical professionals to annotate angiographic image,
    and allows the admin user to upload and delete angiographic images.
  version: 1.0.0
tags:
  - name: Reviewer
    description: Operations related to the Reviewer user role.
  - name: Annotator
    description: Operations related to the Reviewer user role.
  - name: Admin
    description: Operations related to the Admin user role.
paths:
  
