openapi: 3.1.0
info:
  title: Annotations PerfusionTech
  description: |
    This API allows medical professionals to annotate angiographic image,
    and allows the admin user to upload and delete angiographic images.
  version: 1.0.0
tags:
  - name: Reviewer
    description: Operations related to the Reviewer user role.
  - name: Annotator
    description: Operations related to the Reviewer user role.
  - name: Admin
    description: Operations related to the Admin user role.
paths:
  /uploadImage: # If admin ID is required for this endpoint, maybe add it to path: /{adminId}/uploadImage
    put:
      summary: Upload an image
      description: Admin can upload angiographic images for reviewers and annotators to use.
      tags:
        - Admin
      operationId: putImage # Used to make method names, when generating code
      # TODO: identify security measures for such operations
      requestBody:
        content:
          multipart/form-data: # Swagger Docs for file upload
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The image file to upload
                title:
                  type: string
                  description: A title for the image
                text:
                  type: string
                  description: A description of the image
              required:
                - file
      responses:
        '200':    
          description: Image uploaded successfully
  /images/{imageId}:
    delete:
      summary: Delete an image
      description: An admin user role, can delete angiographic images if needed.
      tags:
        - Admin
      operationId: deleteImage
      # TODO: identify security measures for such operations
      parameters:
        - name: imageId
          in: path
          required: true
          schema:
            type: string
          description: The unique image ID for the image to be deleted
      responses: 
        '204': # Successful request, with nothing to be returned to the client
          description: Image was successfully deleted
        '404': 
          description: Image not found
          content: 
            application/json:
              schema: 
                type: string
                example: "Image not found"
        '403':
          description: Forbidden (user not authorized)
          content: 
            application/json:
              schema:
                type: string
                example: "You are not authorized to delete this image"
        '401':
          description: Unauthorized (authentication required)
          content:
            application/json:
              schema:
                type: string
                example: "Authentication required"
        
                
          
          
        
  
